import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "sonner";
import Navbar from "../components/LandingPage/Navbar";
import QueryProvider from "../providers/reactQuery";
import SideBar from "../components/SideBar";
import SideBarWrapper from "../components/SideBarWrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "DevWarrior",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-neutral-950 text-white scrollbar-none`}
      >
        <QueryProvider>
          <Toaster position="top-center" richColors closeButton />
          <Navbar />
          <SideBarWrapper />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
